#!/bin/bash
#SBATCH -N 1          # request 1 node(s)
#SBATCH -p gpu        # gpu for production, gpu_short for test
#SBATCH -t 2-24:00:00 # 5 days is the max for gpu, 1 h max for short

module load python/3.5.2
module load gcc/5.2.0
module load cuda/8.0.44
module load cudnn/8.0-v6.0
module load tensorflow

cd $HOME/Codes/SequentialNeuroSemantics/src/

srun python3 main.py --direction word2brain --model contextual_01 > run_output


echo end of job
